apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ncp-dns-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "ncp-dns-webhook.name" . }}
    chart: {{ include "ncp-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# RoleBinding for reading ConfigMap in kube-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ncp-dns-webhook.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "ncp-dns-webhook.name" . }}
    chart: {{ include "ncp-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "ncp-dns-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# ClusterRoleBinding for auth-delegator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ncp-dns-webhook.fullname" . }}:auth-delegator
  labels:
    app: {{ include "ncp-dns-webhook.name" . }}
    chart: {{ include "ncp-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "ncp-dns-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# ClusterRole for domain-solver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ncp-dns-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "ncp-dns-webhook.name" . }}
    chart: {{ include "ncp-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for domain-solver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ncp-dns-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "ncp-dns-webhook.name" . }}
    chart: {{ include "ncp-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ncp-dns-webhook.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "ncp-dns-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Role for reading secrets in ingress-basic namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ncp-dns-webhook.fullname" . }}-secret-reader
  namespace: {{ .Values.certManager.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
# RoleBinding for the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ncp-dns-webhook.fullname" . }}-secret-reader-binding
  namespace: {{ .Values.certManager.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ncp-dns-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ncp-dns-webhook.fullname" . }}-secret-reader
